name: $(SourceBranchName)-$(Date:dd-MM-yyyy_HH-mm)
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      displayName: 'Install Node.js 12.x'
      versionSpec: '12.x'

  - script: |
      yarn install
    displayName: 'yarn install'

  - script: |
      yarn lint
    displayName: 'yarn lint'

  - script: |
      yarn test:unit
    displayName: 'yarn test:unit'

  - script: |
      yarn build
    displayName: 'yarn build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Application'
    inputs:
      PathtoPublish: dist/
      ArtifactName: application
