name: $(SourceBranchName)-$(Date:dd-MM-yyyy_HH-mm)
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      displayName: 'Install Node.js 12.x'
      versionSpec: '12.x'

  - script: |
      <%= install %>
    displayName: 'Install dependencies'

  - script: |
      <%= lint %>
    displayName: 'Lint'

  - script: |
      <%= test %>
    displayName: 'Unit testing'

  - script: |
      <%= build %>
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Application'
    inputs:
      PathtoPublish: dist/
      ArtifactName: application
