stages:
- test
- build

lint:
  stage: test
  image: node
  script:
    - <%= install %>
    - <%= lint %>

unit:
  stage: test
  image: node
  script:
    - <%= install %>
    - <%= test %>

bundle:
  stage: build
  image: node
  script:
    - <%= install %>
    - <%= build %>
  artifacts:
    paths:
      - dist/
