version: 2.1
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: Install
          command: |
            <%= install %>
      - run:
          name: Lint
          command: |
            <%= lint %>
      - run:
          name: Unit Test
          command: |
            <%= test %>
      - run:
          name: Build
          command: |
            <%= build %>
      - store_artifacts:
          path: dist/
